FROM node:23.7.0 AS build

WORKDIR /usr/local/app

COPY package.json ./
RUN yarn install

COPY src  ./src
COPY public ./public
COPY index.html ./

ARG REACT_APP_PROJECT_ID
ARG REACT_APP_ALCHEMY_KEY
ARG REACT_APP_GRAPHAPI_URL
ARG REACT_APP_SUPPORTED_CHAIN_ID
ARG REACT_APP_MONREGISTERCONTROLLER
ARG REACT_APP_NODE_ENV
ARG REACT_APP_NATIVE_TOKEN
ARG REACT_APP_PUBLICRESOLVER
ARG REACT_APP_MINCOMMITMENTAGE
ARG REACT_APP_MAXCOMMITMENTAGE
ARG REACT_APP_GRACE_PREIOD
ARG REACT_APP_PREMIUM_PERIOD
ARG REACT_APP_TWITTER_URL
ARG REACT_APP_GITHUB_URL
ARG REACT_APP_DISCORD_URL
ARG REACT_APP_CONTRACT_URL
ARG REACT_APP_METADATA_URL

ENV REACT_APP_PROJECT_ID=$REACT_APP_PROJECT_ID
ENV REACT_APP_ALCHEMY_KEY=$REACT_APP_ALCHEMY_KEY
ENV REACT_APP_GRAPHAPI_URL=$REACT_APP_GRAPHAPI_URL
ENV REACT_APP_SUPPORTED_CHAIN_ID=$REACT_APP_SUPPORTED_CHAIN_ID
ENV REACT_APP_MONREGISTERCONTROLLER=$REACT_APP_MONREGISTERCONTROLLER
ENV REACT_APP_NODE_ENV=$REACT_APP_NODE_ENV
ENV REACT_APP_NATIVE_TOKEN=$REACT_APP_NATIVE_TOKEN
ENV REACT_APP_PUBLICRESOLVER=$REACT_APP_PUBLICRESOLVER
ENV REACT_APP_MINCOMMITMENTAGE=$REACT_APP_MINCOMMITMENTAGE
ENV REACT_APP_MAXCOMMITMENTAGE=$REACT_APP_MAXCOMMITMENTAGE
ENV REACT_APP_GRACE_PREIOD=$REACT_APP_GRACE_PREIOD
ENV REACT_APP_PREMIUM_PERIOD=$REACT_APP_PREMIUM_PERIOD
ENV REACT_APP_TWITTER_URL=$REACT_APP_TWITTER_URL
ENV REACT_APP_GITHUB_URL=$REACT_APP_GITHUB_URL
ENV REACT_APP_DISCORD_URL=$REACT_APP_DISCORD_URL
ENV REACT_APP_CONTRACT_URL=$REACT_APP_CONTRACT_URL
ENV REACT_APP_METADATA_URL=$REACT_APP_METADATA_URL

RUN yarn global add vite && yarn build

FROM nginx:latest AS production
COPY --from=build /usr/local/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
