FROM node:23.7.0 AS build

WORKDIR /usr/local/app

COPY . .
RUN npm install --legacy-peer-deps

ARG VITE_APP_PROJECT_ID
ARG VITE_APP_ALCHEMY_KEY
ARG VITE_APP_GRAPHAPI_URL
ARG VITE_APP_SUPPORTED_CHAIN_ID
ARG VITE_APP_MONREGISTERCONTROLLER
ARG VITE_APP_NODE_ENV
ARG VITE_APP_NATIVE_TOKEN
ARG VITE_APP_PUBLICRESOLVER
ARG VITE_APP_MINCOMMITMENTAGE
ARG VITE_APP_MAXCOMMITMENTAGE
ARG VITE_APP_GRACE_PREIOD
ARG VITE_APP_PREMIUM_PERIOD
ARG VITE_APP_TWITTER_URL
ARG VITE_APP_GITHUB_URL
ARG VITE_APP_DISCORD_URL
ARG VITE_APP_CONTRACT_URL
ARG VITE_APP_METADATA_URL

ENV VITE_APP_PROJECT_ID=$VITE_APP_PROJECT_ID
ENV VITE_APP_ALCHEMY_KEY=$VITE_APP_ALCHEMY_KEY
ENV VITE_APP_GRAPHAPI_URL=$VITE_APP_GRAPHAPI_URL
ENV VITE_APP_SUPPORTED_CHAIN_ID=$VITE_APP_SUPPORTED_CHAIN_ID
ENV VITE_APP_MONREGISTERCONTROLLER=$VITE_APP_MONREGISTERCONTROLLER
ENV VITE_APP_NODE_ENV=$VITE_APP_NODE_ENV
ENV VITE_APP_NATIVE_TOKEN=$VITE_APP_NATIVE_TOKEN
ENV VITE_APP_PUBLICRESOLVER=$VITE_APP_PUBLICRESOLVER
ENV VITE_APP_MINCOMMITMENTAGE=$VITE_APP_MINCOMMITMENTAGE
ENV VITE_APP_MAXCOMMITMENTAGE=$VITE_APP_MAXCOMMITMENTAGE
ENV VITE_APP_GRACE_PREIOD=$VITE_APP_GRACE_PREIOD
ENV VITE_APP_PREMIUM_PERIOD=$VITE_APP_PREMIUM_PERIOD
ENV VITE_APP_TWITTER_URL=$VITE_APP_TWITTER_URL
ENV VITE_APP_GITHUB_URL=$VITE_APP_GITHUB_URL
ENV VITE_APP_DISCORD_URL=$VITE_APP_DISCORD_URL
ENV VITE_APP_CONTRACT_URL=$VITE_APP_CONTRACT_URL
ENV VITE_APP_METADATA_URL=$VITE_APP_METADATA_URL

RUN npm run build

FROM nginx:latest AS production
COPY --from=build /usr/local/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
